namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
 
#service:
#  port: 8111
#  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

#image:
 # repository: nginx 
 # tag: alpine
 # pullPolicy: IfNotPresent

replicaCount: 1

resources:
    requests:
            memory: "64Mi"
            cpu: "250m"
    limits:
            memory: "128Mi"
            cpu: "500m"


livenessProbe:
   httpGet:
          path: /healthz

readinessProbe:
   httpGet:
          path: /healthz

#resources:
#  requests:
#    cpu: 50m
#    memory: 256Mi

configmap:
  data: "version: alpine"





