namespace:
  name: prod 
 
service:
  port: 7111
  #type: ClusterIP

#image:
 # repository: mctsm/techtrends 
 # tag: 1.0.0
 # pullPolicy: IfNotPresent

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: "500m"
    memory: "256Mi"
